### ISSUE TITLE
About App Search Results

### ISSUE THREAD

**Issue by dude-shah** [saikou-app/saikou#116]
So I've been using this app, so far this is the best anime app i ever used.

Now to the issue at hand.
I want to ask where does this app fetch it's search results from? 
Its a weird question. Let me explain 
When i searched **Arcane** it didn't show any results, arcane is a popular series also available on both 9anime and Gogo. Searching through the normal search box on top didn't show any result but i clicked on a random anime and then clicked **Wrong Title** there i searched for **Arcane**, the series showed up.
Is this a bug or search results don't use 9anime and Gogo for anime search.

**Comment by brahmkshatriya** [comment]
Saikou is an Anilist client, whatever's available on anilist, will show in the app as well

Anilist didn't add arcane to their site, because it does fall under their criteria

You can still watch stuff present not in anilist on saikou, via using wrong title. But i donot recommend it

& Nor do I plan to add direct searches to play directly from the site itself in this version
