### ISSUE TITLE
Only 25 spaces for favorites ?

### ISSUE THREAD

**Issue by NeoS4ma** [saikou-app/saikou#168]
Don't know if it's an issue or just by design but I only see 25 anime on my favorites ?

**Comment by brahmkshatriya** [comment]
How much does it show on the anilist site?

**Comment by NeoS4ma** [comment]
>

I can't see which one i added favorite on anilist site. Where Can i find it ?

**Comment by brahmkshatriya** [comment]
In your anilist profile,

**Comment by NeoS4ma** [comment]
I only see 4 anime but that's the ones i'm currently watching. I don't see the other 30+ anime in my favorites

**Comment by JimZiii** [comment]
Anilist doesn't have favorites so the favorite function (the heart on a anime page) is just for the app. You can test this yourself by pressing the heart on a show that's not on your anilist, and the number of shows in the "all" category won't increase, which it will if you add it to any of the other categories.
Just clarifying they're separate because of your previous comments, i like having a separate favorite function so I'm not complaining.

But the favorite category only show the first 25 shows you favorite. If i favorite more shows they only appear if i unfavorite some of the first 25 shows, basically making room for the new ones.
So they're there but we can only see the first 25

**Comment by JimZiii** [comment]
Didn't find the favorite list at first on anilist but it works the exact same way on anilist. You can favorite how many you want but you only see the first 25, so to see anything favorited after that you have to remove one or more of the first 25 to make room.

So there's probably nothing you can do about it unless anilist decides to fix or change it.
