### ISSUE TITLE
Mal support (myanimelist)

### ISSUE THREAD

**Issue by berri10010** [saikou-app/saikou#23]
You probably already thought of this and decided not to support it. If so, why?

**Comment by brahmkshatriya** [comment]
Sole reason of not adding MAL is the lack of documentation & Limitations of the API mal provides.
It's API does not permit an app like saikou, though I haven't fully read the T&C.
& the lack of documentation provided by the api, & you can only access some certain stuff, while others are inaccessible 
It's basically mess rn, They need to consider rewriting there API. 

& even If I did add Mal, it will be hard to integrate in the app, since it is still an Anilist Client.
