### ISSUE TITLE
Kamyroll is not working 

### ISSUE THREAD

**Issue by Zeffirelli01** [saikou-app/saikou#247]
### Summary

Kamyroll is not working 

### Reproduction Steps

When I tried to watch any anime it generated a error 

### Expected Result

I expect that it is a bug 

### Actual Result

It is generating this error 

Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
\u0009<html>
\u0009  <head>
\u0009\u0009<meta name="viewport" content="width=device-width, initial-scale=1">
\u0009\u0009<meta charset="utf-8">
\u0009\u0009<title>Application Error</title>
\u0009\u0009<style media="screen">
\u0009\u0009  html,body,iframe {
\u0009\u0009\u0009margin: 0;
\u0009\u0009\u0009padding: 0;
\u0009\u0009  }
\u0009\u0009  html,body {
\u0009\u0009\u0009height: 100%;
\u0009\u0009\u0009overflow: hidden;
\u0009\u0009  }
\u0009\u0009  iframe {
\u0009\u0009\u0009width: 100%;
\u0009\u0009\u0009height: 100%;
\u0009\u0009\u0009border: 0;
\u0009\u0009  }
\u0009\u0009</style>
\u0009  </head>
\u0009  <body>
\u0009\u0009<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
\u0009  </body>
\u0009<"[truncated 6 chars]; line: 1, column: 2]

### Device Information

Samsung j7 nxt
Android 9
1.2.0 1.4

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20220608-095108_Saikou ](https://user-images.githubusercontent.com/106522996/172530936-10e0a29d-63dc-4203-8515-c3593854379c.jpg)

**Comment by Zeffirelli01** [comment]
Maybe it seemed to be a temporary error it started working again

**Comment by hyugogirubato** [comment]
Hey !

I am the developer who takes care of the kamyroll api, I am currently aware of the errors encountered last night and today, I will make sure to make corrections as soon as possible but I will not be able to m Only take care of it tomorrow, so it will be necessary to wait a little before having stable service. currently the service is working again because at each crash I restart it so that it works until the next crash. I have an idea of ​​the error but need to do further analysis to find the error

**Comment by Zeffirelli01** [comment]
Ok thank you for telling so should I close the issue ?

**Comment by hyugogirubato** [comment]
Yes you can close this issue, I just made api fixes to take care of these errors, normally there should be no more api crashes
