### ISSUE TITLE
Set Quality to Auto as default

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#27]
Can we get an option in upcoming settings features to set Quality to Auto as default because after quitting the app whenever I resume the episode it starts asking me for quality again.

**Comment by brahmkshatriya** [comment]
Click on "make default" when selecting a server, this way it will not ask for server selection again
![image](https://user-images.githubusercontent.com/69040506/156361183-cc7fc104-79d9-4fa9-8b06-91b8a8103e76.png)

Settings will not include default server selection since it can different for each anime. It will however have a default source option & Default Quality for Multi Quality Servers.

**Comment by brahmkshatriya** [comment]
> Well then I think there's a bug in that because whenever I exit the app it again asks me to select the quality option.

Please provide a video reference
