### ISSUE TITLE
chapters that aren't hole nubers aren't counted as read

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#297]
### Summary

chapters that aren't hole nubers aren't counted as read

### Reproduction Steps

read chapter 21.1

### Expected Result

it should've said i've read 21.1

### Actual Result

it said i read 21
and when i left and reentered the manga it put me on chapter 22, not 21.1

### Device Information

saikou version:1.2.0.15/1.2.0.12
brand: samsung
android version: 5.1.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
~~"Whole" numbers, not "hole".~~

> it should've said i've read 21.1

It's because Anilist doesn't support fractional chapter numbers for updating the progress. Only whole numbers are supported. Can't do anything about it unfortunately.

> and when i left and reentered the manga it put me on chapter 22, not 21.1

If the chapter order is `21, 21.1, 22`, and you have reached the last page in chapter 21.1, the next chapter will be loaded (22) automatically even if you re-open the manga.
