### ISSUE TITLE
One Piece on Kamyroll

### ISSUE THREAD

**Issue by Marco-9456** [saikou-app/saikou#369]
### Summary

One Piece on Kamyroll is still broken

### Reproduction Steps

Go to settings and change language to arME or arSA.

### Expected Result

To show one piece in arabic

### Actual Result

Black screen and then send back to the app home screen.

### Device Information

Saikou Version: 1.2.0.18
Device: samsung t2s
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

In the last release it was completely broken but now from my testing it's working just for the English and German language.

**Comment by brahmkshatriya** [comment]
Nah i wont be fixing this.
The bug is related Android's core memory handling for sending an object as parceble, it probably has some limit, and when it is crossed the app crashes without any logs

I removed the description from episodes for any series that has more than 700episodes 
This fixed one-piece, for now but as episode increase it might break again 

I can't fix this without changing the whole data passing between activities
