### ISSUE TITLE
Not everything from the favorites tab is shown

### ISSUE THREAD

**Issue by twenty-fiv** [saikou-app/saikou#519]
### Summary

Not all the manga i have in the favorite tab is shown. Only 25 without loading the rest

### Reproduction Steps

I recently downloaded the app and have only tried to move my manga library to it. I only searched by name and then clicked the heart. But by the 25th one it stopped showing them in the tab labeled favourites yet when i looked up a manga the heart was clicked

### Expected Result

To have the manga appear in the tab

### Actual Result

Only the first 25 i looked up were in there

### Device Information

Saikou Version: 1.2.0.24
Device: samsung a52sxq
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by yellowHatpro** [comment]
Same behavior for me as well. It seems to me a problem with the graphql query. It happens for both manga and anime.

**Comment by yellowHatpro** [comment]
@brahmkshatriya can it be due to graphql queries, like only 25 entries can be fetched or something? Because we can favorite entities (e.g., we have saved 26 mangas, and if we see favs, it will show 25, but if we remove any one, the one which was not there earlier will come). 
Could it be due to pageSize or something similar?

**Comment by brahmkshatriya** [comment]
Anilist has limited the amount of how many favs you can add, to increase that limit you need to become an anilist supporter
