### ISSUE TITLE
Changing Default Anime Source in settings not working

### ISSUE THREAD

**Issue by TimmoTismo** [saikou-app/saikou#552]
### Summary

Changing the default anime source in settings does do anything and reverts back to the original default source

### Reproduction Steps

Go to Settings -> Anime -> Click drop down menu for default anime source -> Select a different source from the one already selected (by default its AllAnime) -> Press the back button in the top right

### Expected Result

Change the default anime source from AllAnime to a different source

### Actual Result

Default anime source reverts back to AllAnime upon reentering the settings page

### Device Information

Saikou Version: 1.2.0.24
Device: samsung o1s
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
I can't reproduce this issue. This is what I've done:

1. Check what the default source was (it was AllAnime).
2. Click on an anime (e.g. Spy x Family).
3. Check source (it was AllAnime).
4. Go back to settings and change default source to Gogo.
5. Open Spy x Family
6. Check source (it was AllAnime)[1].
7. Open a different anime.
8. Check source (it was Gogo).

[1] - This was caused because of the cache. If you close the app and try to open any anime/manga again, it should show the default source you selected.

**Comment by scrazzz** [comment]
> Default anime source reverts back to AllAnime upon reentering the settings page

I want to note that this doesn't happen to me. The source stays as Gogo after changing it from AllAnime.
