### ISSUE TITLE
Every anime source (except zoro partially) not working

### ISSUE THREAD

**Issue by Aeropro4** [saikou-app/saikou#559]
### Summary

As mentioned in title none anime source is working in which Allanime, Gogo, Marin, Animepahe, Consumbili & KickassAnime (except zoro is working But gives an error)

### Reproduction Steps

(I am using Chainsaw Man For an example)
1) For Gogo:
(https://user-images.githubusercontent.com/113044496/219875361-a287077a-0212-4895-b6fe-84cd395f8888.jpg)
When Selecting an episode, it starts searching for servers but this errors comes and Streamsb is gone
2) Allanime:
(https://user-images.githubusercontent.com/113044496/219875514-39b9f1c7-f835-4794-bf60-f26d2d638a37.jpg)
Well nothing to say :(
3) Zoro:
(https://user-images.githubusercontent.com/113044496/219875548-55d35158-6529-43ad-a7da-b4db4a536198.jpg)
The episodes are working but this error comes and in some episodes subs are absent
4) Animepahe (my favourite):
(https://user-images.githubusercontent.com/113044496/219875612-ca050051-f628-42aa-be85-83f1070802c7.jpg)
Nothing just blank
5) KickAssAnime:
(https://user-images.githubusercontent.com/113044496/219875681-2482ca01-3846-4794-bd84-be1c3997e7ab.jpg)
I Don't use it but what's the fault in telling

### Expected Result

Well anyone should work and that would be fine and zoro is ok but it has its own problems as mentioned above

### Actual Result

Written above :|

### Device Information

Version: 1.2.0.24 (With installed Latest Artifact)
Brand: Samsung
architecture: ARMv8-A
OS: 13

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

### Additional Information

Umm nothing else just pls try to fix and yeah not wanna say it but if it can happen then pls add Animesuge(https://animesuge.to/) Cause it already scrapes from 9anime so i think it would be easy to just scrape from this site 
AND i searched the issues but all have mentioned only one or 2 so i just compiled them together

**Comment by sjain3097** [comment]
Any update on this?

**Comment by TobyBridle** [comment]
> Any update on this?

Gogo should have some more streams now that streamsb is working. AllAnime has been fixed. KAA is in progress but I don't have much time to work on it so it'll be a little while.

**Comment by Khaled-Haroun** [comment]
I honestly realized this problem today, but I mostly use the zoro website because that was the only one that worked for me.... but today I came across multiple problems. First off, the video wouldn't let me skip ahead. When I try to move the time to after the intro the video would return to 00:00. The subtitles were not in the video (mentioned above). Lastly, I would open an episode to choose the server that I want to use and I would find that there was no  server to choose. Basically the list was empty. The last one didn't happen as much as the previous one, but I said it because I thought that I should atleast mention it because I didn't see anybody talking about it
