### ISSUE TITLE
Date for completed animes not saving, instead just putting today's date

### ISSUE THREAD

**Issue by Asmodeus-AvatarofLust** [saikou-app/saikou#62]
Whenever I try to put a Complete status on an anime I have finished watching, and me putting a date that I actually finished (Not recently, multiple months/years ago), starting date becomes blank and finished date becomes today's date.

**Comment by brahmkshatriya** [comment]
Can you provide a screen recording to better explain what exactly is happening?

**Comment by DARK-TESTING** [comment]
The issue is when i update the anime's start and end in the 
search anime->anime it gets saved. But when I check from the 
home page->anime list->completed 
it show that start and end time in anilist hasn't been updated yet though the anime gets updated. If I force update the time in anilist it show that in the app

Before saving in-app:
![Screenshot_2022-03-17-00-45-55-990_ani saikou](https://user-images.githubusercontent.com/101746198/158670945-239eca80-7106-4b25-b0ab-c5f69bab99d8.jpg)

After saving in-app:
![Screenshot_2022-03-17-00-46-36-087_ani saikou](https://user-images.githubusercontent.com/101746198/158670959-8e4fe7a4-2261-476e-a1cc-93bca165544b.jpg)

After saving in anilist:
![Screenshot_2022-03-17-00-47-00-111_com android chrome](https://user-images.githubusercontent.com/101746198/158670967-234e297c-9b24-4c2c-8470-0edc7aabaf17.jpg)

![Screenshot_2022-03-17-00-47-13-220_com android chrome](https://user-images.githubusercontent.com/101746198/158670975-8b20e573-dba9-43e8-bc06-80186e9e35d7.jpg)

**Comment by Fireboy6** [comment]
> Can you provide a screen recording to better explain what exactly is happening?

Why everything in Saikou is Large Text i noticed that compared to Anilist he showed.
