### ISSUE TITLE
Anilist login not working 

### ISSUE THREAD

**Issue by CdtShin42** [saikou-app/saikou#808]
### Summary

I'm trying to login to anilist but not working

### Reproduction Steps

I'm trying to login to anilist but not working

### Expected Result

Please fix it 

### Actual Result

I'm trying to login to anilist but not working

### Device Information

Latest version
Oppo a16e

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
You're not following the issue pattern. You haven't filled in the reproduction steps and the below steps properly.

Don't open another issue without giving proper details.

**Comment by scrazzz** [comment]
Instead of opening another issue, try this:

1) open your browser and login to anilist (even if you are already logged in, just open `anilist.co` in your browser).
2) open saikou
3) click Login
4) you should be logged in instantly/automatically


If the above steps still doesn't work, then ask about it in the discord server.

**Comment by Sadwhy** [comment]
Ps. You **MUST** have Chrome set as your default browser.

**Comment by Adolar0042** [comment]
it's not a must, many other browsers work too. Unfortunately some browsers like opera gx removed the stuff that is needed to properly work

**Comment by Sadwhy** [comment]
Afaik brave and opera gx don't work. Using chrome always fixed the problem. So I say it's a must.
